import React, { useState } from 'react';
import { 
  CheckCircle2, 
  AlertTriangle, 
  AlertOctagon, 
  Copy, 
  Check, 
  Printer,
  ArrowLeft, 
  PhoneCall, 
  Sparkles,
  Info,
  MapPin,
  Radio,
  Newspaper,
  Activity
} from 'lucide-react';
import { TriageResult, PatientProfile } from '../types/triage';

interface TriageResultsProps {
  result: TriageResult;
  profile: PatientProfile;
  onReset: () => void;
  onSaveToHistory?: (result: TriageResult) => void;
  isSaved?: boolean;
}

export const TriageResults: React.FC<TriageResultsProps> = ({
  result,
  profile,
  onReset
}) => {
  // Toggle: 'simple' ("Explain Like I'm 12") vs 'clinical' ("Explain Like a Clinician")
  const [readingMode, setReadingMode] = useState<'simple' | 'clinical'>('simple');
  const [copied, setCopied] = useState(false);

  // Status configuration based on urgency tier
  const getStatusInfo = () => {
    switch (result.urgencyTier) {
      case 'EMERGENCY':
        return {
          title: 'Emergency Medical Care Needed',
          tag: 'Emergency Alert',
          color: 'bg-red-600 text-white',
          bannerBg: 'bg-red-50 border-red-200 text-red-900',
          icon: AlertOctagon,
          actionText: 'Please seek emergency care or dial 911 immediately.'
        };
      case 'HIGH_ALERT':
        return {
          title: 'Contact Your Doctor Promptly',
          tag: 'High Alert',
          color: 'bg-amber-600 text-white',
          bannerBg: 'bg-amber-50 border-amber-200 text-amber-900',
          icon: AlertTriangle,
          actionText: 'Call your pediatrician, OB/GYN, or specialist office today.'
        };
      case 'MODERATE':
        return {
          title: 'Contact Clinic Today for Advice',
          tag: 'Moderate Priority',
          color: 'bg-yellow-600 text-white',
          bannerBg: 'bg-yellow-50 border-yellow-200 text-yellow-900',
          icon: Info,
          actionText: 'Reach out to your clinic advice line or schedule a same-day check.'
        };
      case 'LOW_HOME_CARE':
      default:
        return {
          title: 'Home Care & Careful Monitoring',
          tag: 'Home Care',
          color: 'bg-emerald-600 text-white',
          bannerBg: 'bg-emerald-50 border-emerald-200 text-emerald-900',
          icon: CheckCircle2,
          actionText: 'You can likely care for this comfortably at home with watchful waiting.'
        };
    }
  };

  const status = getStatusInfo();
  const StatusIcon = status.icon;

  const handleCopyDoctorNote = () => {
    const textToCopy = `
PATIENT SYMPTOM SUMMARY (Prepared for Doctor/Clinic)
---------------------------------------------------
Patient: ${profile.name} (${profile.ageYears ?? 1} years old)
Location: ${profile.locationCity || 'Local Community'}${profile.locationCoordinates ? ` (GPS: ${profile.locationCoordinates.lat.toFixed(4)}°, ${profile.locationCoordinates.lng.toFixed(4)}°, ±${profile.locationCoordinates.accuracy || 10}m)` : ''}
Evaluation Tier: ${result.urgencyTier}
Protocol: ${result.protocolMatched}

SBAR CLINICAL SUMMARY:
${result.clinicalExplanation.sbarSummary}

PROTOCOL / CODE:
${result.clinicalExplanation.protocolCode}

RECOMMENDED ACTION:
${result.clinicalExplanation.recommendedAction}
---------------------------------------------------
Generated by NicheCare Multimodal Clinical Engine
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const simpleSteps: string[] = (result.plainExplanation as any).simpleNextSteps || [
    result.plainExplanation.whatToDoNext || 'Follow the suggested guidance and reach out to your doctor if symptoms do not improve.'
  ];

  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-fadeIn pb-12">
      {/* Top Back / Action bar */}
      <div className="flex items-center justify-between no-print">
        <button
          onClick={onReset}
          className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-600 hover:text-slate-900 bg-white px-3 py-1.5 rounded-xl border border-slate-200 transition-colors shadow-2xs"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Start Over</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyDoctorNote}
            className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-700 bg-white hover:bg-slate-50 px-3 py-1.5 rounded-xl border border-slate-200 transition-colors shadow-2xs"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-teal-600" />
                <span className="text-teal-700">Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-500" />
                <span>Copy for Doctor</span>
              </>
            )}
          </button>

          <button
            onClick={() => window.print()}
            className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-700 bg-white hover:bg-slate-50 px-3 py-1.5 rounded-xl border border-slate-200 transition-colors shadow-2xs"
          >
            <Printer className="w-3.5 h-3.5 text-slate-500" />
            <span>Print</span>
          </button>
        </div>
      </div>

      {/* 1. Main Status Result Banner */}
      <div className={`p-6 rounded-2xl border ${status.bannerBg} shadow-xs space-y-3`}>
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className={`p-3 rounded-2xl ${status.color} shadow-xs`}>
              <StatusIcon className="w-6 h-6" />
            </div>
            <div>
              <span className={`inline-block px-2.5 py-0.5 rounded-full text-[11px] font-extrabold uppercase tracking-wider mb-1 ${status.color}`}>
                {status.tag}
              </span>
              <h1 className="text-xl sm:text-2xl font-black text-slate-900">
                {status.title}
              </h1>
            </div>
          </div>
        </div>

        <p className="text-sm font-semibold text-slate-800 pt-1">
          {status.actionText}
        </p>

        <div className="text-xs text-slate-600 pt-1 border-t border-slate-200/60 flex items-center justify-between flex-wrap gap-2">
          <span>Evaluated for: <strong>{profile.name}</strong></span>
          <span>Protocol: <strong>{result.protocolMatched}</strong></span>
        </div>
      </div>

      {/* 2. Disease Suggestions & Candidate Considerations (Includes Local Outbreak Matches) */}
      {result.candidateConsiderations && result.candidateConsiderations.length > 0 && (
        <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-3">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Activity className="w-4 h-4 text-teal-600" />
              <span>Disease Suggestions & Evaluated Considerations</span>
            </h3>
            <span className="text-[11px] font-semibold text-slate-500 bg-slate-100 px-2.5 py-0.5 rounded-full">
              Matched to Clinical Protocols & Local Outbreak News
            </span>
          </div>

          <p className="text-xs text-slate-500">
            Based on the symptoms provided, clinical guidelines, and current circulating disease patterns in your community, these conditions are considered:
          </p>

          <div className="space-y-2.5 pt-1">
            {result.candidateConsiderations.map((item, idx) => (
              <div 
                key={idx} 
                className={`p-3.5 rounded-xl border transition-all ${
                  item.isOutbreakLinked 
                    ? 'bg-purple-50/70 border-purple-200' 
                    : 'bg-slate-50/70 border-slate-200'
                }`}
              >
                <div className="flex items-start justify-between gap-2 mb-1.5 flex-wrap">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-sm font-bold text-slate-900">
                      {item.name}
                    </span>
                    {item.isOutbreakLinked && (
                      <span className="inline-flex items-center gap-1 text-[10px] font-extrabold uppercase tracking-wider px-2 py-0.5 rounded-md bg-purple-600 text-white shadow-2xs">
                        <Radio className="w-2.5 h-2.5" />
                        <span>Local Outbreak Match</span>
                      </span>
                    )}
                  </div>
                  <span className={`text-[11px] font-bold px-2 py-0.5 rounded-full shrink-0 ${
                    item.isOutbreakLinked ? 'bg-purple-100 text-purple-800' : 'bg-slate-200 text-slate-700'
                  }`}>
                    {item.tier}
                  </span>
                </div>

                <p className="text-xs text-slate-700 leading-relaxed">
                  {item.rationale}
                </p>

                {item.outbreakSource && (
                  <div className="mt-2 pt-2 border-t border-purple-100 flex items-center gap-1.5 text-[11px] text-purple-900 font-medium">
                    <Newspaper className="w-3 h-3 text-purple-600" />
                    <span>Public Health Bulletin: <strong>{item.outbreakSource}</strong></span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 3. Local Disease Surveillance & Health Department Bulletin */}
      {((result.outbreakSignals && result.outbreakSignals.length > 0) || result.outbreakSignal) && (
        <div className="bg-gradient-to-r from-teal-50/80 to-blue-50/80 rounded-2xl p-5 border border-teal-200 space-y-3">
          <div className="flex items-start justify-between gap-2">
            <div className="flex items-center gap-2 text-xs font-extrabold text-teal-950 uppercase tracking-wider">
              <Radio className="w-4 h-4 text-teal-600 animate-pulse" />
              <span>Local Disease Surveillance & Health Department Bulletin</span>
            </div>
            <span className="text-[11px] font-semibold text-teal-800 bg-teal-100/70 px-2.5 py-0.5 rounded-full flex items-center gap-1.5 flex-wrap">
              <MapPin className="w-3 h-3 text-teal-700" />
              <span>{profile.locationCity || 'Your Community'}</span>
              {profile.locationCoordinates && (
                <span className="text-[10px] bg-white/80 px-1.5 py-0.2 rounded font-mono text-teal-900 border border-teal-200/60">
                  GPS: {profile.locationCoordinates.lat.toFixed(2)}°, {profile.locationCoordinates.lng.toFixed(2)}°
                </span>
              )}
            </span>
          </div>

          <div className="space-y-2.5">
            {(result.outbreakSignals || [result.outbreakSignal!]).filter(Boolean).map((sig) => (
              <div key={sig.id} className="p-3.5 bg-white/90 rounded-xl border border-teal-100 space-y-1.5 text-xs text-slate-700 shadow-2xs">
                <div className="flex items-center justify-between gap-2 flex-wrap">
                  <span className="font-bold text-teal-950 text-sm">
                    {sig.pathogen}
                  </span>
                  <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-teal-100 text-teal-800">
                    {sig.severity}
                  </span>
                </div>
                <p className="font-medium text-slate-800">
                  "{sig.headline}"
                </p>
                <p className="text-slate-600 leading-relaxed">
                  {sig.relevanceNote}
                </p>
                {sig.clinicalAction && (
                  <p className="text-teal-900 bg-teal-50 p-2 rounded-lg font-medium border border-teal-100/60">
                    💡 <strong>Clinical Context:</strong> {sig.clinicalAction}
                  </p>
                )}
                <div className="pt-1 text-[11px] text-slate-400 flex items-center justify-between flex-wrap gap-2">
                  <span>Reporting Agency: {sig.source}</span>
                  <span>{sig.dateReported}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 4. Dual Reading Mode Switcher: "Simple Summary" vs "Doctor's Note" */}
      <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-3">
          <div>
            <h2 className="text-sm font-bold text-slate-900">
              Guidance & Explanations
            </h2>
            <p className="text-xs text-slate-500">
              Choose how you want to read this result:
            </p>
          </div>

          {/* Clean Dual Toggle */}
          <div className="flex items-center bg-slate-100 p-1 rounded-xl shrink-0 self-start sm:self-auto">
            <button
              onClick={() => setReadingMode('simple')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                readingMode === 'simple'
                  ? 'bg-white text-teal-700 shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Sparkles className="w-3.5 h-3.5 text-teal-600" />
              <span>Simple Summary</span>
            </button>

            <button
              onClick={() => setReadingMode('clinical')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                readingMode === 'clinical'
                  ? 'bg-white text-slate-900 shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <span>Doctor's Note</span>
            </button>
          </div>
        </div>

        {/* View A: Simple Summary (Explain Like I'm 12) */}
        {readingMode === 'simple' && (
          <div className="space-y-4 animate-fadeIn">
            <div className="p-4 rounded-xl bg-teal-50/60 border border-teal-100">
              <h3 className="font-bold text-sm text-teal-950 mb-1">
                {result.plainExplanation.headline}
              </h3>
              <p className="text-xs sm:text-sm text-teal-900 leading-relaxed">
                {result.plainExplanation.whatItMeans}
              </p>
            </div>

            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                Next steps you should take:
              </h4>
              <ul className="space-y-1.5 text-xs sm:text-sm text-slate-700">
                {simpleSteps.map((step, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="w-5 h-5 rounded-full bg-teal-100 text-teal-700 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* View B: Doctor's Note (Clinical SBAR Format) */}
        {readingMode === 'clinical' && (
          <div className="space-y-4 animate-fadeIn">
            <div className="p-4 rounded-xl bg-slate-900 text-slate-100 font-mono text-xs space-y-3 leading-relaxed">
              <div className="text-teal-400 font-bold border-b border-slate-800 pb-1 flex items-center justify-between">
                <span>CLINICAL SBAR HANDOFF</span>
                <span className="text-[10px] text-slate-400">Protocol: {result.clinicalExplanation.protocolCode}</span>
              </div>
              <p className="text-slate-300">
                {result.clinicalExplanation.sbarSummary}
              </p>
              <div className="pt-2 border-t border-slate-800 text-[11px] text-slate-400 space-y-1">
                <div>
                  <span className="text-slate-200 font-semibold">Recommended Action: </span>
                  {result.clinicalExplanation.recommendedAction}
                </div>
                {result.clinicalExplanation.pathophysiology && (
                  <div>
                    <span className="text-slate-200 font-semibold">Differential / Protocol: </span>
                    {result.clinicalExplanation.pathophysiology}
                  </div>
                )}
              </div>
            </div>

            <p className="text-xs text-slate-500">
              You can read this exact note to your doctor's office or triage nurse on the phone.
            </p>
          </div>
        )}
      </div>

      {/* 5. Home Care Steps (Shown ONLY if safe for home care) */}
      {result.homeCareGuidance && result.homeCareGuidance.length > 0 && (
        <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-3">
          <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            <span>Comfort Measures & Home Care</span>
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {result.homeCareGuidance.map((item, idx) => {
              const text = typeof item === 'string' ? item : (item as any).step || (item as any).detail;
              return (
                <div key={idx} className="p-3.5 rounded-xl bg-emerald-50/50 border border-emerald-100 text-xs text-emerald-900 font-medium">
                  {text}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* 6. Watch-Out Signs (When to call doctor immediately) */}
      <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-xs space-y-3">
        <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-amber-500" />
          <span>When to seek faster medical attention</span>
        </h3>

        <ul className="space-y-1.5 text-xs text-slate-700">
          {result.plainExplanation.watchOutSigns.map((sign, idx) => (
            <li key={idx} className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0 mt-1.5" />
              <span>{sign}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* 6. Primary Action Buttons */}
      <div className="flex flex-col sm:flex-row items-center gap-3 pt-2">
        <button
          onClick={onReset}
          className="w-full sm:flex-1 py-3 px-4 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs uppercase tracking-wider transition-colors shadow-xs"
        >
          Check Another Symptom
        </button>

        {result.urgencyTier !== 'LOW_HOME_CARE' && (
          <a
            href="tel:911"
            className="w-full sm:w-auto py-3 px-5 rounded-xl bg-red-600 hover:bg-red-700 text-white font-bold text-xs uppercase tracking-wider transition-colors shadow-xs flex items-center justify-center gap-1.5"
          >
            <PhoneCall className="w-3.5 h-3.5" />
            <span>Emergency 911</span>
          </a>
        )}
      </div>

      {/* Medical disclaimer */}
      <p className="text-center text-[11px] text-slate-400 pt-2">
        This symptom checker is for informational triage guidance grounded in verified medical protocols (AAP, ACOG, ADA). It does not substitute for an in-person doctor evaluation.
      </p>
    </div>
  );
};
